var settings = {
  "Permission": "Everyone",
  "PermissionInfo": "",
  "Command": "!lootdrop",
  "Cooldown": 20,
  "DropTime": 60,
  "SleepMin": 10,
  "SleepMax": 30,
  "LotteryWinner": 0.25,
  "LotteryPrice": 500,
  "JoinReward": 150,
  "CooldownMessage": "/me $(Display) got a cooldown on $(CooldownLeft) seconds.",
  "NoPermissionMessage": "/me $(Display) got no permission to use $(Command).",
  "DropClosingMessage1": "The drops have ended, not enough entries to draw winners",
  "DropClosingMessage2": "The drops have ended! $(LotteryWinners) won $(LotteryReward) $(Currency)",
  "JoinedDropMessage": "$(Display) joined the drop and got $(JoinReward) $(Currency)",
  "NoDropMessage": "No drops available...",
  "AlreadyInDropMessage": "/me $(Display) has already joined the drop!",
  "DropStartingMessage": "Drops are now active for $(DropTime) seconds! Type $(Command) to join"
};