var settings = {
  "Permission": "Everyone",
  "PermissionInfo": "",
  "Command": "!gamble",
  "MinGamble": 1,
  "PersonalCooldown": 30,
  "ChannelCooldown": 5,
  "WinChanse": 48,
  "2xWinChanse": 2,
  "LossRisk": 48,
  "NoPermissionMessage": "$(Display), you have no permission to use the command!",
  "ShowPermissionMessage": true,
  "PersonalCooldownMessage": "$(Display), you have $(CooldownLeft) seconds left on your cooldown!",
  "ShowPersonalCooldownMessage": true,
  "ChannelCooldownMessage": "$(Display), there is a channel cooldown on $(ChannelCooldownLeft) seconds!",
  "ShowChannelCooldownMessage": true,
  "WinMessage": "$(Display) won a value of $(Amount) $(Currency)",
  "ShowWinMessage": true,
  "2xWinMessage": "$(Display) won a value of $(Amount) $(Currency)",
  "Show2xWinMessage": true,
  "LossMessage": "$(Display) lost a value of $(Amount) $(Currency)",
  "ShowLossMessage": true,
  "NotEnoughMessage": "$(Display), you have a total of $(CurrencyAmount) $(Currency) which means that you are unable to gamble $(Amount) $(Currency)...",
  "ShowNotEnoughMessage": true,
  "MinGambleMessage": "$(Display), you are not able to gamble less than $(MinGamble) $(Currency)...",
  "ShowMinGambleMessage": true
};